[package]
name = "dg_xch_serialize"
description = "Low Level Support Package for dg_xch_utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
log = "0.4.28"
serde = { version = "1.0.228", features = ["derive"] }
time = "0.3.44"